### PR TITLE
Update to 4.9-6

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@jdblischak Ready to merge :)

**Comment by jdblischak** [comment]
@dpryan79 You're quick! :-)

**Comment by dpryan79** [comment]
I have to put together a training, so I'm glued to github as a distraction :P

**Comment by jdblischak** [comment]
> I have to put together a training, so I'm glued to github as a distraction :P

@dpryan79 I can totally relate! GitHub is a wonderful distraction. Good luck with writing your training materials!

**Pull request merged**
